import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const apiCategory = (label: string, dir: string) => ({
  type: 'category' as const,
  label,
  link: {type: 'doc' as const, id: `reference/api/${dir}/index`},
  items: [{type: 'autogenerated' as const, dirName: `reference/api/${dir}`}],
});

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/module-formats',
        'getting-started/bundlers-and-serverless',
        'getting-started/responsible-use',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/card-notation',
        'concepts/packed-card-input',
        'concepts/packed-poker-state',
        'concepts/float64-icm-input',
        'concepts/hand-rank-labels',
        'concepts/range-equity',
        'concepts/sparse-range-input',
        'concepts/numerical-semantics',
        'concepts/errors-and-validation',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/index',
        'guides/decide-action',
        'guides/monte-carlo-equity',
        'guides/batch-equity',
        'guides/icm-and-side-pots',
        'guides/range-equity-exact',
        'guides/preflop-equity-matrix',
        'guides/tournament-runouts-and-bots',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Types',
          link: {type: 'doc', id: 'reference/types/index'},
          items: [{type: 'autogenerated', dirName: 'reference/types'}],
        },
        {
          type: 'doc',
          id: 'reference/api/index',
          label: 'API overview',
        },
        apiCategory('Hands & equity', 'hands-and-equity'),
        apiCategory('Monte Carlo', 'monte-carlo'),
        apiCategory('Strategy', 'strategy'),
        apiCategory('Pot & EV', 'pot-and-ev'),
        apiCategory('Stacks & display', 'stacks-and-display'),
        apiCategory('Heuristics & draws', 'heuristics-and-draws'),
        apiCategory('Reverse implied', 'reverse-implied'),
        apiCategory('Statistics & risk', 'statistics-and-risk'),
        apiCategory('Kelly & jam', 'kelly-and-jam'),
        apiCategory('GTO frequencies', 'gto-frequencies'),
        apiCategory('Sizing & commitment', 'sizing-and-commitment'),
        apiCategory('Fold equity', 'fold-equity'),
        apiCategory('Multiway', 'multiway'),
        apiCategory('ICM', 'icm'),
        apiCategory('Side pots', 'side-pots'),
        apiCategory('Tournament ICM', 'cooperative-icm'),
        apiCategory('Exact runouts', 'combinatorics-exact'),
        apiCategory('Subgame & ranges', 'subgame-theory'),
        apiCategory('Range tools', 'range-tools'),
        apiCategory('Board texture', 'board-texture'),
        apiCategory('Opponent modeling', 'opponent-modeling'),
      ],
    },
  ],
};

export default sidebars;
