import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import families from './src/data/api-families.json';

type Family = {slug: string; title: string; functions: string[]};
type Category = {slug: string; title: string; suit: string; blurb: string; families: Family[]};
type Section = {title: string; categories: Category[]};

// The API reference is generated from the same data as the pages, so it cannot drift.
const apiItems = (families.sections as Section[]).flatMap((section) => [
  {
    type: 'html' as const,
    value: section.title,
    className: 'sidebar-section-label',
    defaultStyle: true,
  },
  ...section.categories.map((cat) => ({
    type: 'category' as const,
    label: cat.title,
    link: {type: 'doc' as const, id: `reference/api/${cat.slug}/index`},
    items: cat.families.map((fam) => `reference/api/${cat.slug}/${fam.slug}`),
  })),
]);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/module-formats',
        'getting-started/bundlers-and-serverless',
        'getting-started/responsible-use',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: [
        'guides/monte-carlo-equity',
        'guides/range-equity-exact',
        'guides/icm-and-side-pots',
        'guides/preflop-equity-matrix',
        'guides/batch-equity',
        'guides/decide-action',
        'guides/tournament-runouts-and-bots',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/card-notation',
        'concepts/packed-card-input',
        'concepts/packed-poker-state',
        'concepts/float64-icm-input',
        'concepts/hand-rank-labels',
        'concepts/range-equity',
        'concepts/sparse-range-input',
        'concepts/numerical-semantics',
        'concepts/errors-and-validation',
      ],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      link: {type: 'doc', id: 'reference/api/index'},
      items: apiItems,
    },
    {
      type: 'category',
      label: 'Types',
      link: {type: 'doc', id: 'reference/types/index'},
      items: [{type: 'autogenerated', dirName: 'reference/types'}],
    },
  ],
};

export default sidebars;
