name: Documentation site

on:
  push:
    paths:
      - 'Website/**'
      - 'NPM/native/**'
      - 'NPM/index.d.ts'
      - 'NPM/encode.js'
      - 'NPM/encode.d.ts'
  pull_request:
    paths:
      - 'Website/**'
      - 'NPM/native/**'
      - 'NPM/index.d.ts'
      - 'NPM/encode.js'
      - 'NPM/encode.d.ts'

defaults:
  run:
    working-directory: Website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: Website/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm check:docs
      - run: pnpm build
